<?php

declare(strict_types=1);

namespace App\Data\Api;

use AndyDefer\DomainStructures\Abstracts\AbstractData;

/**
 * Data DTO for UserData.
 *
 * @author Generated by DirectiveForge
 */
final class UserData extends AbstractData
{
    public function __construct(
        // TODO: Add properties with readonly modifier
       
    ) { }
}