<?php

declare(strict_types=1);

namespace App\Services;

/**
 * Service class for NotificationSenderService.
 *
 * @author Generated by DirectiveForge
 */
final class NotificationSenderService
{
    /**
     * Create a new service instance.
     */
    public function __construct()
    {
        // TODO: Inject dependencies
    }
}