<?php

declare(strict_types=1);

namespace App\Http\Requests;

use AndyDefer\Actions\Http\Requests\AbstractRequest;
use AndyDefer\DomainStructures\Abstracts\AbstractRecord;
use AndyDefer\DomainStructures\Utils\EmptyRecord;

/**
 * Form request for LoginRequest.
 *
 * @author Generated by DirectiveForge
 */
final class LoginRequest extends AbstractRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, array<int, string>>
     */
    public function rules(): array
    {
        return [];
    }

    /**
     * Get the record instance for this request.
     *
     * Returns an EmptyRecord by default. Override this method
     * to return a custom Record with validated data.
     */
    public function getRecord(): AbstractRecord
    {
        return new EmptyRecord();
    }
}