<?php

declare(strict_types=1);

namespace App\Data;

use AndyDefer\DomainStructures\Abstracts\AbstractData;

/**
 * Data DTO for ProductData.
 *
 * @author Generated by DirectiveForge
 */
final class ProductData extends AbstractData
{
    public function __construct(
        // TODO: Add properties with readonly modifier
       
    ) { }
}