<?php

declare(strict_types=1);

namespace App\Configs\Database;

use AndyDefer\DomainStructures\Abstracts\AbstractConfig;

/**
 * Configuration class for MysqlConfig.
 *
 * @author Generated by DirectiveForge on 2026-06-10 16:30:16
 */
final class MysqlConfig extends AbstractConfig
{
    // TODO: Add configuration methods
}