<?php

declare(strict_types=1);

namespace App\ValueObjects\User;

use AndyDefer\DomainStructures\Abstracts\AbstractValueObject;

/**
 * Value Object for EmailAddressVO.
 *
 * @author Generated by DirectiveForge on 2026-06-10 16:30:16
 */
final class EmailAddressVO extends AbstractValueObject
{
    public function __construct(
        // TODO: Add properties with readonly modifier
    ) {
        // TODO: Add validation logic
    }
}